######## User
### 회원 가입
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "name": "test",
  "password": "test123!",
  "nationality": "KOREA",
  "language": "KO"
}

### 로그인
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test123!"
}