spring:
  datasource:
    url: jdbc:mysql://localhost:3306/translation_chat
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1212

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: "CHAT_ROOM"
    consumer:
      group-id: "group_1"
      auto-offset-reset: earliest
      enable-auto-commit: true
      max-poll-records: 10

  main:
    allow-bean-definition-overriding: true

jwt:
  secret: Y2hvcHBhLWRvbnQtYml0ZS1tZS1zcHJpbmctYm9vdC1qd3QtdGVzdC1zZWNyZXQta2V5LWNob3BwYS1kb250LWJpdGUtbWUtc3ByaW5nLWJvb3Qtand0LXRlc3Qtc2VjcmV0LWtleQo=